[package]
name = "rust_ray"
version = "0.5.0"
authors = ["Stewart Charles <trio.of.four@gmail.com>"]

[dependencies]
image = "0.17.0"
nalgebra = "0.5.1"
time = "0.1"
rand = "0.4"
rayon = "1.0.3"
lazy_static = "1.0"
